version: '3.7'

services:
        react-app-docker:
                container_name: react
                build: 
                        dockerfile: Dockerfile
                        context: .
                volumes:
                        - '.:/app'
                        - '/app/node_modules'
                ports:
                        - "${HOST_PORT}:${PORT}"
                environment:
                        - CHOKIDAR_USERPOLLING=true

