version: '3.7'

services:
        react-server-docker:
                container_name: react
                image: markdoblefilo/react-server-docker:1.0
                volumes:
                        - '.:/app'
                        - '/app/node_modules'
                ports:
                        - 3000:3000
                environment:
                        - CHOKIDAR_USERPOLLING=true

