version: '3.7'

services:

  react-dev:
    container_name: react-server-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3005:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
